apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-2
  name: test-2
  namespace: test-2
spec:
  replicas: 50
  selector:
    matchLabels:
      app: test-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-2
    spec:
      containers:
      - image: tkgi-harbor-01a.corp.local/library/nginx
        name: nginx
        resources: {}
status: {}
