apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-3
  name: test-3
  namespace: test-3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-3
        test: "2"
    spec:
      containers:
      - image: tkgi-harbor-01a.corp.local/library/nginx
        name: nginx
        resources: {}
status: {}
