apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-4
  name: test-4
  namespace: test-4
spec:
  replicas: 50
  selector:
    matchLabels:
      app: test-4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-4
    spec:
      containers:
      - image: tkgi-harbor-01a.corp.local/library/nginx
        name: nginx
        resources: {}
status: {}
